CREATE DATABASE TbtGlobal;

go
use TbtGlobal;

CREATE TABLE Grade(
Id INT IDENTITY (1,1) NOT NULL, 
Code VARCHAR(10) UNIQUE NOT NULL,
Name VARCHAR(200) NOT NULL, 
CONSTRAINT PK_Grade PRIMARY KEY (Id));

CREATE TABLE Student(
Id INT IDENTITY(1,1) NOT NULL,
IdGrade INT NOT NULL,
Name VARCHAR(200) NOT NULL,
Document VARCHAR(50) NOT NULL,
Phone VARCHAR (20) UNIQUE NOT NULL,
Adress VARCHAR (100) DEFAULT 'Sin Dirección' NOT NULL,
CONSTRAINT PK_Student PRIMARY KEY (Id),
CONSTRAINT FK_Grade FOREIGN KEY (IdGrade) REFERENCES Grade (Id)
);


CREATE TABLE Class(
Id INT IDENTITY(1,1) NOT NULL,
Name VARCHAR(200) UNIQUE NOT NULL,
Description VARCHAR(300) DEFAULT 'Clase sin descripción' NOT NULL,
CONSTRAINT PK_Class PRIMARY KEY (Id));


CREATE TABLE Schedule(
Id INT IDENTITY(1,1) NOT NULL,
ScheduleDate DATETIME NOT NULL,
IdStudent INT NOT NULL,
IdClass INT NOT NULL,
Credits VARCHAR(25) NOT NULL,
Observations VARCHAR (200) DEFAULT 'Sin observación de agenda' NOT NULL,
CONSTRAINT PK_Schedule PRIMARY KEY (Id),
CONSTRAINT FK_ScheduleStudent FOREIGN KEY (IdStudent) REFERENCES Student (Id),
CONSTRAINT FK_ScheduleClass FOREIGN KEY (IdClass) REFERENCES Class (Id));